"use client"
import './globals.css'
import React from 'react';
import { Inter } from 'next/font/google'
import ReactDOM from 'react-dom/client';
import { NextUIProvider } from '@nextui-org/react';
import { Providers } from '@/store/providers'
import 'bootstrap/dist/css/bootstrap.min.css';
import Navsbar from "@/component/Navsbar";


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <React.StrictMode>
          <NextUIProvider>
            <Navsbar/>
              {children}
          </NextUIProvider>
          </React.StrictMode>
      </body>
    </html>
  )
}
